
setwd("~/tra_business_cycle")
rev_sectors_s <- read.csv("~/tra_business_cycle/rev_sectors_s.csv")
attach(rev_sectors_s)

rev_sectors_s <- ts(data = rev_sectors_s, start = 1998, end = 2014, frequency = 4)
lagri <- ts(lagri, start = 1998, end = 2014, frequency = 4)
# transform variables into logs
lagri <- log(agri)
lmining <- log(mining)
lelecgas <- log(elecgas)
lwater <- log(water)
lconstruction <- log(construction)
ltrade <- log(trade)
ltransport <- log(transport)
laccomodation <- log(accomodation)
lict <- log(ict)
lfinance <- log(finance)
lreal_estates <- log(lreal_estates)
lprofessional <- log(professional)
ladministration <- log(administration)
lpublic_admin <- log(lpublic_admin)
leducation <- log(education)
lhealth <- log(health)
lrecreation <- log(recreation)
lother_service <- log(other_service)
lhouseholds <- log(households)
lextraterritorial <- log(extraterirritorial)
ltotal <- log(total)

